ALTER TABLE encounters ADD COLUMN IF NOT EXISTS summary TEXT NOT NULL DEFAULT '';
ALTER TABLE encounters ADD COLUMN IF NOT EXISTS open_question TEXT NOT NULL DEFAULT '';
ALTER TABLE encounters ADD COLUMN IF NOT EXISTS promised_next_step TEXT NOT NULL DEFAULT '';
ALTER TABLE encounters ADD COLUMN IF NOT EXISTS changed_since_last TEXT NOT NULL DEFAULT '';
